---
init_lib: /home/yongheng/Squirrel/squirrel_srcs/SQLite/fuzz_root/init_lib
pragma: /home/yongheng/Squirrel/squirrel_srcs/SQLite/fuzz_root/pragma
db: mysql
passwd: ''
user_name: yongheng
host: localhost
sock_path: /tmp/mysql.sock
db_prefix: test
